services:
  - name: quiz-backend
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: "32"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: UPLOAD_DIR
        value: /opt/render/uploads
      - key: MAX_IMAGE_SIZE_MB
        value: 5
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
      - key: DATABASE_URL
        value: postgres://neondb_owner:npg_1qsapTojtMB8@ep-holy-heart-a4alz82t-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
        sync: true
      - key: CLOUDINARY_URL
        value: cloudinary://637167941541637:ph-Jre4_0OXZT5exhkbLy8cHWrU@dmohrr8hq
        sync: false
    plan: free